# Generated by Django 4.2.3 on 2023-07-13 09:32

from django.db import migrations, models


class Origin(models.TextChoices):
    DEFAULT = "default", "Créé normalement via les emplois"
    PE_APPROVAL = "pe_approval", "Créé lors d'un import d'Agrément Pole Emploi"
    # On November 30th, 2021, AI were delivered approvals without a diagnosis.
    AI_STOCK = "ai_stock", "Créé lors de l'import du stock AI"
    ADMIN = "admin", "Créé depuis l'admin"


def migrate_approvals_from_ai_stock_and_pe_approval_origin(apps, schema_editor):
    # About 20 cases in PROD: fix is easy, investigation in progress to isolate source
    Approval = apps.get_model("approvals", "Approval")
    to_update = Approval.objects.filter(
        eligibility_diagnosis__isnull=False, origin__in=(Origin.PE_APPROVAL, Origin.AI_STOCK)
    )
    print(f"\n{len(to_update)} approvals with an eligibility diagnosis (AI stock or former PE approval):")
    print(
        "\n".join([f"pk:{approval.pk}, number:{approval.number}, origin:{approval.origin}" for approval in to_update])
    )
    to_update.update(origin=Origin.ADMIN)
    print(
        f"Updated {len(to_update)} approvals with an eligibility diagnosis (AI stock or former PE approval):"
        f" set origin to: {Origin.ADMIN}"
    )


def migrate_approvals_without_diagnosis_with_bad_origin(apps, schema_editor):
    # 13.07.2023: one single case in DB
    Approval = apps.get_model("approvals", "Approval")
    to_update = Approval.objects.filter(eligibility_diagnosis=None, origin__in=(Origin.ADMIN, Origin.DEFAULT))
    print(f"\n{len(to_update)} approvals without any eligibility diagnosis (former PE approval):")
    print(
        "\n".join([f"pk:{approval.pk}, number:{approval.number}, origin:{approval.origin}" for approval in to_update])
    )
    to_update.update(origin=Origin.PE_APPROVAL)
    print(
        f"Updated {len(to_update)} approvals without any eligibility diagnosis (former PE approval): "
        f"set origin to: {Origin.PE_APPROVAL}"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0009_suspension_cannot_start_in_the_future"),
    ]

    operations = [
        migrations.RunPython(migrate_approvals_from_ai_stock_and_pe_approval_origin),
        migrations.RunPython(migrate_approvals_without_diagnosis_with_bad_origin),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("eligibility_diagnosis__isnull", False), ("origin__in", ["admin", "default"])),
                    models.Q(("eligibility_diagnosis", None), ("origin__in", ["pe_approval", "ai_stock"])),
                    _connector="OR",
                ),
                name="approval_eligibility_diagnosis",
                violation_error_message="Incohérence entre l'origine du PASS IAE et la présence d'un diagnostic d'éligibilité",  # noqa: E501
            ),
        ),
    ]
